'use client'

import { useEffect, useMemo, useState } from 'react'
import {
  ArrowRight, Heart, Menu, Minus, Package, Search, ShoppingBag, Sparkles, X, Zap,
} from 'lucide-react'

type Product = { id:number; name:string; category:string; price:number; oldPrice?:number; color:string; image:string; badge?:string; description:string; sizes:string[]; stock:number; lowStockThreshold:number }
type CartLine = { id:number; size:string; quantity:number }

const initialProducts: Product[] = [
  { id:1, name:'Body Negro Escote V', category:'Bodies', price:24990, oldPrice:29990, color:'Negro', badge:'-17%', image:'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?auto=format&fit=crop&w=900&q=85', description:'Body clásico y versátil para combinar con todo.', sizes:['S','M','L'], stock:2, lowStockThreshold:3 },
  { id:2, name:'Catsuit Negro Manga Larga', category:'Catsuits', price:38990, color:'Negro', badge:'Nuevo', image:'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=900&q=85', description:'Una silueta cómoda y poderosa para salir o armar tu look diario.', sizes:['S','M','L','XL'], stock:8, lowStockThreshold:3 },
  { id:3, name:'Musculosa Básica Bordó', category:'Conjuntos', price:16990, color:'Bordó', image:'https://images.unsplash.com/photo-1564257577054-3e2b7c1b5f3b?auto=format&fit=crop&w=900&q=85', description:'Infaltable de temporada, suave y fácil de combinar.', sizes:['Único','S','M'], stock:5, lowStockThreshold:3 },
  { id:4, name:'Conjunto Cut Out', category:'Conjuntos', price:42990, oldPrice:49990, color:'Negro', badge:'-14%', image:'https://images.unsplash.com/photo-1506629905607-d9f3bb9f7b36?auto=format&fit=crop&w=900&q=85', description:'Conjunto protagonista con recortes y calce femenino.', sizes:['S','M','L'], stock:2, lowStockThreshold:3 },
  { id:5, name:'Body Manga Larga', category:'Bodies', price:27990, color:'Negro', image:'https://images.unsplash.com/photo-1618244972963-dbee1a7edc95?auto=format&fit=crop&w=900&q=85', description:'Prenda cómoda para usar sola o debajo de tus outfits favoritos.', sizes:['S','M','L','XL'], stock:8, lowStockThreshold:3 },
  { id:6, name:'Top Corset Bordó', category:'Conjuntos', price:22990, color:'Bordó', image:'https://images.unsplash.com/photo-1605763240000-7e93b172d754?auto=format&fit=crop&w=900&q=85', description:'Textura y estructura para elevar cualquier conjunto.', sizes:['S','M','L'], stock:2, lowStockThreshold:3 },
]

export default function Page() {
  const [products, setProducts] = useState(initialProducts)
  const [cart, setCart] = useState<CartLine[]>([])
  const [search, setSearch] = useState('')
  const [category, setCategory] = useState('Todos')
  const [categorySection, setCategorySection] = useState('Todos')
  const [carouselIndex, setCarouselIndex] = useState<Record<string, number>>({})
  const [cartOpen, setCartOpen] = useState(false)
  const [admin, setAdmin] = useState(false)
  const [logged, setLogged] = useState(false)
  const [login, setLogin] = useState(false)
  const [notice, setNotice] = useState('')
  const [copy, setCopy] = useState({ title: 'Moda que inspira tu estilo.', description: 'Indumentaria femenina seleccionada con amor. Diseños únicos, calidad y envíos a todo el país.', footer: 'HEY BBY! Somos Daiquiar. Diseño y calidad a precios únicos. CABA, Buenos Aires. Envíos a todo el país.', whatsapp: '5491100000000', shippingThreshold: 75000, correoArgentinoUrl: 'https://www.correoargentino.com.ar/formularios/cpa', benefits: [{ title: 'Envío gratis', description: 'En compras superiores a $75.000' }, { title: 'Compra simple', description: 'Coordinamos tu pedido por WhatsApp' }, { title: 'Atención cercana', description: 'Te ayudamos a elegir tu look' }] })

  useEffect(() => {
    const saved = window.localStorage.getItem('daiquiar-copy')
    if (saved) setCopy(current => ({ ...current, ...JSON.parse(saved) }))
  }, [])

  const filtered = useMemo(() => products.filter(p => (category === 'Todos' || p.category === category) && p.name.toLowerCase().includes(search.toLowerCase())), [products, category, search])
  const categoryProducts = useMemo(() => products.filter(product => product.category === categorySection), [products, categorySection])
  const categories = ['Bodies', 'Catsuits', 'Conjuntos']
  const cartProducts = cart.map(line => ({ ...line, product: products.find(p => p.id === line.id) })).filter(line => line.product) as (CartLine & { product: Product })[]
  const total = cartProducts.reduce((sum, line) => sum + line.product.price * line.quantity, 0)

  const chooseCategory = (next:string) => { setCategory(next); setCategorySection(next); document.getElementById('catalogo')?.scrollIntoView({ behavior: 'smooth' }) }
  const moveCarousel = (name:string, direction:number, total:number) => setCarouselIndex(current => ({ ...current, [name]: ((current[name] ?? 0) + direction + total) % total }))
  const add = (id:number, size:string, quantity:number) => { setCart(current => { const existing = current.find(line => line.id === id && line.size === size); return existing ? current.map(line => line === existing ? { ...line, quantity: line.quantity + quantity } : line) : [...current, { id, size, quantity }] }); setNotice('Producto agregado al carrito'); setTimeout(() => setNotice(''), 2000) }
  const remove = (id:number, size:string) => setCart(current => current.filter(line => !(line.id === id && line.size === size)))
  const changeQuantity = (id:number, size:string, delta:number) => setCart(current => current.map(line => line.id === id && line.size === size ? { ...line, quantity: Math.max(1, line.quantity + delta) } : line))
  const whatsapp = () => {
    const text = `Hola Daiquiar Indumentaria! Quiero hacer este pedido:\n\n${cartProducts.map(line => `• ${line.product.name} · Talle ${line.size} · ${line.quantity} unidad(es) — $${(line.product.price * line.quantity).toFixed(2)}`).join('\n')}\n\nTotal estimado: $${total.toFixed(2)}\n\nMis datos de entrega:\nNombre: \nDirección: \nTeléfono: `
    window.open(`https://wa.me/${copy.whatsapp.replace(/\D/g, '')}?text=${encodeURIComponent(text)}`, '_blank')
  }
  const saveProduct = (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); const data = new FormData(e.currentTarget); const next:Product = { id:Date.now(), name:String(data.get('name')), category:String(data.get('category')), price:Number(data.get('price')), color:'Nuevo', image:String(data.get('image')) || initialProducts[0].image, description:String(data.get('description')) || 'Producto agregado desde el panel.', sizes:String(data.get('sizes') || 'S, M, L').split(',').map(size => size.trim()).filter(Boolean), stock: 0, lowStockThreshold: 3 }; setProducts(p => [next, ...p]); e.currentTarget.reset() }

  return <main className="min-h-screen bg-background text-foreground">
    {notice && <div className="fixed top-5 left-1/2 z-50 -translate-x-1/2 rounded-full bg-foreground px-5 py-3 text-sm text-background shadow-xl">{notice}</div>}
    <header className="sticky top-0 z-30 border-b border-border/70 bg-background/95 backdrop-blur">
      <div className="mx-auto flex max-w-6xl items-center gap-5 px-5 py-5">
        <button className="md:hidden" aria-label="Abrir menú"><Menu size={21}/></button>
        <a href="#inicio" className="mr-auto text-2xl font-black tracking-[0.14em] text-[#7b1028]">DAIQUIAR</a>
        <nav className="hidden items-center gap-7 text-sm font-medium md:flex"><a href="#catalogo">Novedades</a><a href="#catalogo">Bodies</a><a href="#catalogo">Catsuits</a><a href="#catalogo">Conjuntos</a></nav>
        <div className="hidden items-center gap-3 md:flex"><div className="flex w-52 items-center gap-2 rounded-full border border-border bg-muted/50 px-3 py-2"><Search size={16} className="text-muted-foreground"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar productos..." className="w-full bg-transparent text-xs outline-none"/></div></div>
        <button aria-label="Carrito" className="relative" onClick={()=>setCartOpen(true)}><ShoppingBag size={21}/>{cart.length>0 && <span className="absolute -right-2 -top-2 flex h-4 w-4 items-center justify-center rounded-full bg-primary text-[10px] text-primary-foreground">{cart.length}</span>}</button>
      </div>
      <div className="flex gap-2 overflow-x-auto border-t border-border/50 px-5 py-3 md:hidden"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar productos..." className="min-w-0 flex-1 rounded-full border bg-muted/50 px-4 py-2 text-sm outline-none"/></div>
    </header>

    <section id="inicio" className="bg-[linear-gradient(110deg,#f5e6d8_0%,#fff8f1_48%,#e9c8bd_100%)]"><div className="mx-auto grid max-w-6xl items-center gap-10 px-5 py-16 md:grid-cols-2 md:py-24"><div><p className="mb-4 text-xs font-semibold uppercase tracking-[0.25em] text-primary">Colección tendencia</p><h1 className="max-w-xl text-balance text-5xl font-black leading-[0.98] tracking-tight md:text-7xl">{copy.title}</h1><p className="mt-6 max-w-lg text-lg leading-8 text-muted-foreground">{copy.description}</p><div className="mt-8 flex flex-wrap gap-3"><a href="#catalogo" className="inline-flex items-center gap-3 rounded-xl bg-primary px-6 py-3 font-semibold text-primary-foreground">Comprar ahora <ArrowRight size={18}/></a><a href="#colecciones" className="rounded-xl border border-border bg-background px-6 py-3 font-semibold">Ver lookbook</a></div></div><div className="relative"><img src="https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?auto=format&fit=crop&w=1000&q=85" alt="Modelo usando la nueva colecci����n" className="h-[390px] w-full rounded-[2rem] object-cover shadow-2xl md:h-[470px]"/></div></div></section>

    <section id="colecciones" className="mx-auto max-w-6xl px-5 py-16"><div className="mb-8 max-w-xl"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-primary">Elegí tu categoría</p><h2 className="mt-2 text-4xl font-bold tracking-tight">Encontrá tu próximo look</h2><p className="mt-3 text-muted-foreground">Mirá algunos ejemplos y entrá a cada categoría para descubrir toda la variedad disponible.</p></div><div className="mb-8 flex flex-wrap gap-2"><button onClick={()=>chooseCategory('Todos')} className={`rounded-full px-5 py-2.5 text-sm font-semibold transition ${category==='Todos'?'bg-primary text-primary-foreground':'border border-border bg-background hover:border-primary hover:text-primary'}`}>Todos</button>{categories.map(name=><button key={name} onClick={()=>chooseCategory(name)} className={`rounded-full px-5 py-2.5 text-sm font-semibold transition ${category===name?'bg-primary text-primary-foreground':'border border-border bg-background hover:border-primary hover:text-primary'}`}>{name}</button>)}</div><div className="grid gap-6 md:grid-cols-3">{categories.map(name => { const items = products.filter(product => product.category === name); const current = carouselIndex[name] ?? 0; const preview = items.length ? items[current % items.length] : products[0]; return <CategoryCard key={name} name={name} product={preview} count={items.length} onSelect={() => chooseCategory(name)} onPrevious={() => moveCarousel(name, -1, Math.max(items.length, 1))} onNext={() => moveCarousel(name, 1, Math.max(items.length, 1))}/> })}</div></section>

    <section id="catalogo" className="bg-muted/35 px-5 py-16"><div className="mx-auto max-w-6xl"><div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.25em] text-primary">Elegidos para vos</p><h2 className="mt-2 text-4xl font-bold tracking-tight">Nuevos ingresos</h2></div><div className="flex items-center gap-2 overflow-x-auto">{['Todos','Bodies','Catsuits','Conjuntos'].map(c=><button key={c} onClick={()=>chooseCategory(c)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm ${category===c?'bg-primary text-primary-foreground':'bg-background border border-border'}`}>{c}</button>)}</div></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(p=><ProductCard key={p.id} product={p} add={add}/>)}</div>{filtered.length===0 && <p className="rounded-2xl border border-dashed border-border p-10 text-center text-muted-foreground">Todavía no hay productos en esta categoría.</p>}</div></section>

    <section className="mx-auto grid max-w-6xl gap-8 px-5 py-16 sm:grid-cols-3">{copy.benefits.map(({ title, description }, index) => { const Icon = [Package, Zap, Heart][index] ?? Package; return <div key={title} className="text-center"><div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-full bg-primary/10 text-primary"><Icon size={24}/></div><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p></div> })}</section>

    <section className="bg-[#0d0d0d] px-5 py-16 text-background"><div className="mx-auto max-w-6xl"><div className="grid gap-10 md:grid-cols-[1.1fr_1fr_1fr]"><div><p className="text-2xl font-black tracking-[0.14em] text-[#7b1028]">DAIQUIAR</p><p className="mt-4 max-w-sm text-sm leading-7 text-background/65">{copy.footer}</p><div className="mt-6 flex items-center gap-4"><a aria-label="Instagram de Daiquiar" href="https://instagram.com/daiquiar.indumentaria" target="_blank" rel="noreferrer" className="text-background/75 hover:text-primary"><Heart size={22}/></a><a aria-label="WhatsApp de Daiquiar" href={`https://wa.me/${copy.whatsapp.replace(/\D/g, '')}`} target="_blank" rel="noreferrer" className="rounded-full bg-primary px-4 py-2 text-xs font-bold text-primary-foreground">WhatsApp</a></div></div><div><h3 className="text-lg font-bold">Información</h3><div className="mt-4 flex flex-wrap gap-2"><a href="#pagos" className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Medios de pago</a><a href="#envios" className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Envíos</a><a href="#devoluciones" className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Devoluciones</a></div></div><div><h3 className="text-lg font-bold">Preguntas frecuentes</h3><div className="mt-4 space-y-3 text-sm text-background/70"><details><summary className="cursor-pointer font-semibold text-background">¿Cómo hago un pedido?</summary><p className="mt-2 leading-6">Agregá tus prendas al carrito y confirmá el pedido por WhatsApp.</p></details><details><summary className="cursor-pointer font-semibold text-background">¿Cómo se paga?</summary><p className="mt-2 leading-6">Trabajamos con transferencia bancaria y efectivo. El pedido se confirma con 50% de anticipo.</p></details><details><summary className="cursor-pointer font-semibold text-background">¿Hacen envíos?</summary><p className="mt-2 leading-6">Sí, realizamos envíos a todo el país y coordinamos los detalles por WhatsApp.</p></details></div></div></div><div className="mt-12 grid gap-4 border-t border-background/10 pt-8 text-sm text-background/65 md:grid-cols-3"><div id="pagos"><p className="font-bold text-background">Medios de pago</p><p className="mt-1">Transferencia bancaria o efectivo.</p></div><div id="envios"><p className="font-bold text-background">Envíos</p><p className="mt-1">CABA, Buenos Aires y todo el país.</p></div><div id="devoluciones"><p className="font-bold text-background">Política de devoluciones</p><p className="mt-1">Consultanos dentro de los 7 días de recibido el pedido.</p></div></div><p className="mt-8 border-t border-background/10 pt-6 text-xs text-background/40">© 2026 Daiquiar Indumentaria. Todos los derechos reservados.</p></div></section>

    {cartOpen && <Cart items={cartProducts} total={total} threshold={copy.shippingThreshold} correoArgentinoUrl={copy.correoArgentinoUrl} remove={remove} changeQuantity={changeQuantity} close={()=>setCartOpen(false)} whatsapp={whatsapp}/>} 
  </main>
}

function CategoryCard({name,product,count,onSelect,onPrevious,onNext}:{name:string;product:Product;count:number;onSelect:()=>void;onPrevious:()=>void;onNext:()=>void}) { return <article className="group relative overflow-hidden rounded-3xl border border-border bg-foreground"><img src={product.image} alt={`${name}: ${product.name}`} className="h-80 w-full object-cover transition duration-500 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-foreground/90 via-foreground/15 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-5 text-background"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#ead7bd]">{count} productos</p><h3 className="mt-1 text-2xl font-bold">{name}</h3><p className="mt-1 text-sm text-background/75">Ejemplo: {product.name}</p><div className="mt-4 flex items-center gap-2"><button aria-label={`Foto anterior de ${name}`} onClick={onPrevious} className="rounded-full bg-background/20 px-3 py-2 backdrop-blur">‹</button><button onClick={e=>{e.preventDefault()}} className="flex-1 rounded-full bg-[#ead7bd] px-4 py-2 text-sm font-bold text-foreground">Ver todos</button><button aria-label={`Siguiente foto de ${name}`} onClick={onNext} className="rounded-full bg-background/20 px-3 py-2 backdrop-blur">›</button></div></div></article> }
function ProductCard({product,add}:{product:Product;add:(id:number,size:string,quantity:number)=>void}) { const [size,setSize] = useState(product.sizes[0]); const [quantity,setQuantity] = useState(1); return <article className="group overflow-hidden rounded-2xl border border-border bg-background"><div className="relative h-72 overflow-hidden"><img src={product.image} alt={product.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/>{product.badge&&<span className={`absolute left-3 top-3 rounded-full px-3 py-1 text-xs font-bold ${product.badge==='Nuevo'?'bg-emerald-500 text-white':'bg-primary text-primary-foreground'}`}>{product.badge}</span>}</div><div className="p-5"><p className="text-xs uppercase tracking-wider text-muted-foreground">{product.category}</p><h3 className="mt-1 font-bold">{product.name}</h3><p className="mt-2 line-clamp-1 text-sm text-muted-foreground">{product.description}</p>{product.stock === 0 ? <p className="mt-3 text-sm font-semibold text-muted-foreground">Sin stock</p> : product.stock <= product.lowStockThreshold && <p className="mt-3 text-sm font-semibold text-primary">Quedan {product.stock} unidades</p>}<div className="mt-4 flex gap-2"><select aria-label={`Talle de ${product.name}`} value={size} onChange={e=>setSize(e.target.value)} className="rounded-lg border bg-background px-2 py-2 text-sm">{product.sizes.map(option=><option key={option}>{option}</option>)}</select><div className="flex items-center rounded-lg border"><button aria-label="Disminuir unidades" onClick={()=>setQuantity(value=>Math.max(1,value-1))} className="px-3">−</button><span className="min-w-8 text-center text-sm">{quantity}</span><button aria-label="Aumentar unidades" onClick={()=>setQuantity(value=>value+1)} className="px-3">+</button></div></div><button disabled={product.stock === 0} onClick={()=>add(product.id,size,quantity)} className="mt-3 w-full rounded-xl bg-primary py-3 text-sm font-semibold text-primary-foreground disabled:cursor-not-allowed disabled:opacity-40">{product.stock === 0 ? 'Sin stock' : 'Agregar al carrito'}</button><div className="mt-4 flex items-center gap-2"><span className="text-lg font-bold">${product.price.toFixed(2)}</span>{product.oldPrice&&<del className="text-sm text-muted-foreground">${product.oldPrice.toFixed(2)}</del>}</div></div></article> }
function Overlay({children,close}:{children:React.ReactNode;close:()=>void}) { return <div className="fixed inset-0 z-40 bg-foreground/40 p-4" onClick={close}><div onClick={e=>e.stopPropagation()} className="mx-auto mt-8 max-h-[90vh] max-w-lg overflow-auto rounded-2xl bg-background p-6 shadow-2xl">{children}</div></div> }
function Cart({items,total,threshold,correoArgentinoUrl,remove,changeQuantity,close,whatsapp}:{items:(CartLine & {product:Product})[];total:number;threshold:number;correoArgentinoUrl:string;remove:(id:number,size:string)=>void;changeQuantity:(id:number,size:string,delta:number)=>void;close:()=>void;whatsapp:()=>void}) { const correoDisponible = total >= threshold; return <Overlay close={close}><div className="flex items-center justify-between"><h2 className="text-2xl font-bold">Tu carrito</h2><button onClick={close}><X/></button></div>{items.length===0?<p className="py-12 text-center text-muted-foreground">Todavía no agregaste productos.</p>:<><div className="mt-6 space-y-4">{items.map(line=><div className="flex items-center gap-3" key={`${line.id}-${line.size}`}><img src={line.product.image} alt="" className="h-16 w-16 rounded-lg object-cover"/><div className="min-w-0 flex-1"><p className="truncate font-semibold">{line.product.name}</p><p className="text-sm text-muted-foreground">Talle {line.size} · ${line.product.price.toFixed(2)}</p><div className="mt-2 flex items-center gap-3"><button onClick={()=>changeQuantity(line.id,line.size,-1)} className="rounded border px-2">−</button><span>{line.quantity}</span><button onClick={()=>changeQuantity(line.id,line.size,1)} className="rounded border px-2">+</button><button onClick={()=>remove(line.id,line.size)} className="ml-auto text-muted-foreground"><Minus size={16}/></button></div></div></div>)}</div><div className="mt-7 flex justify-between border-t pt-5 text-lg font-bold"><span>Total estimado</span><span>${total.toFixed(2)}</span></div><div className="mt-5 rounded-xl border border-border bg-muted/40 p-4"><p className="text-sm font-semibold">Elegí cómo coordinar el envío</p><p className="mt-1 text-xs text-muted-foreground">{correoDisponible ? `Por superar el monto mínimo de $${threshold.toLocaleString('es-AR')}, solo podés elegir Correo Argentino.` : `Correo Argentino se habilita desde $${threshold.toLocaleString('es-AR')}.`}</p><div className="mt-3 grid gap-2"><button onClick={whatsapp} hidden={correoDisponible} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#25D366] py-3 font-bold text-white">Coordinar por WhatsApp <ArrowRight size={18}/></button>{correoDisponible ? <a href={correoArgentinoUrl} target="_blank" rel="noreferrer" className="flex w-full items-center justify-center gap-2 rounded-xl border border-primary py-3 font-bold text-primary">Enviar por Correo Argentino <ArrowRight size={18}/></a> : <p className="text-center text-xs text-muted-foreground">Para compras menores, coordiná el envío por WhatsApp.</p>}</div></div><p className="mt-3 text-center text-xs text-muted-foreground">Los pedidos se confirman con 50% de anticipo. Podés pagar por transferencia o efectivo.</p></>}</Overlay> }
function Login({close,onLogin}:{close:()=>void;onLogin:()=>void}) { return <Overlay close={close}><div className="flex justify-between"><h2 className="text-2xl font-bold">Acceso admin</h2><button onClick={close}><X/></button></div><p className="mt-2 text-sm text-muted-foreground">Demo: usá cualquier email y contraseña.</p><form className="mt-6 space-y-4" onSubmit={e=>{e.preventDefault();onLogin()}}><input required type="email" placeholder="Email" className="w-full rounded-xl border bg-muted/30 px-4 py-3 outline-none"/><input required type="password" placeholder="Contraseña" className="w-full rounded-xl border bg-muted/30 px-4 py-3 outline-none"/><button className="w-full rounded-xl bg-primary py-3 font-semibold text-primary-foreground">Entrar al panel</button></form></Overlay> }
function Admin({products,logged,close,save,remove,login}:{products:Product[];logged:boolean;close:()=>void;save:(e:React.FormEvent<HTMLFormElement>)=>void;remove:(id:number)=>void;login:()=>void}) { return <Overlay close={close}>{!logged?<div className="text-center"><h2 className="text-2xl font-bold">Panel de administración</h2><p className="mt-3 text-muted-foreground">Ingresá para administrar tus productos.</p><button onClick={login} className="mt-6 rounded-xl bg-primary px-6 py-3 font-semibold text-primary-foreground">Iniciar sesión</button></div>:<><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-widest text-primary">Modo admin</p><h2 className="text-2xl font-bold">Gestionar catálogo</h2></div><button onClick={close}><X/></button></div><form onSubmit={save} className="mt-6 grid gap-3"><input required name="name" placeholder="Nombre del producto" className="rounded-xl border px-4 py-3"/><select name="category" className="rounded-xl border px-4 py-3"><option>Bodies</option><option>Catsuits</option><option>Conjuntos</option></select><input required name="price" type="number" step="0.01" placeholder="Precio" className="rounded-xl border px-4 py-3"/><input required name="sizes" placeholder="Talles disponibles: S, M, L" className="rounded-xl border px-4 py-3"/><input name="image" placeholder="URL de imagen" className="rounded-xl border px-4 py-3"/><textarea name="description" placeholder="Descripción" className="rounded-xl border px-4 py-3"/><button className="rounded-xl bg-primary py-3 font-semibold text-primary-foreground">+ Agregar producto</button></form><div className="mt-8 space-y-3"><h3 className="font-bold">Productos activos ({products.length})</h3>{products.map(p=><div key={p.id} className="flex items-center gap-3 border-t pt-3"><img src={p.image} alt="" className="h-10 w-10 rounded object-cover"/><span className="flex-1 truncate text-sm">{p.name}</span><button onClick={()=>remove(p.id)} className="text-xs text-destructive">Eliminar</button></div>)}</div></>}</Overlay> }
